### ISSUE TITLE
new workflow?

### ISSUE THREAD

**Issue by M-Evans** [cs-si-ucr/CS14-Spring15#1]
Make changeds directly to gh-pages, then run `update.sh` in the project root, `git add *`, commit, push, and it's live. :smile:

**Comment by CrazyWearsPJs** [comment]
What advantages does this have over 

``` sh
mkdocs gh-deploy
```

**Comment by M-Evans** [comment]
I didn't know about that. :sweat_smile:

**Comment by M-Evans** [comment]
(without knowledge of gh-deploy)

**Comment by M-Evans** [comment]
Fixing now.

**Comment by M-Evans** [comment]
fixed
